db:
  url: jdbc:postgresql://localhost:5432/db
  user: root
  password: root
  schema: vkr
application:
  name: @name@
  version: @version@
  type: production
  port: 443
  domain: tdms.tu-bryansk.ru
  protocol: https

spring:
  application:
    name: ${application.name}
  main:
    allow-circular-references: true
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    hikari:
      schema: ${db.schema}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  flyway:
    url: ${db.url}
    user: ${db.user}
    password: ${db.password}
    schemas: ${db.schema}
    locations: db.migration
server:
  port: ${application.port}
  address: ${application.domain}
  compression:
    enabled: true
