create table vkr.user
(
    id           integer primary key generated by default as identity,
    login        text                        not null unique,
    password     text                        not null,
    full_name    text                        not null,
    mail         text                        not null unique,
    number_phone text                        not null unique,
    create_at    timestamp(6) with time zone not null,
    update_at    timestamp(6) with time zone

)
